name: Docker Image

on:
  workflow_run:
    workflows: [ "Run tests" ]
    types:
      - completed
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: release

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image (base, used in tests)
        run: |
          docker build \
            -f docker/postgres/13/Dockerfile \
            -t gristfdw-base:bullseye-postgres13-multicorn2.4 \
            .
      - name: Build the Docker image
        run: |
          docker build \
            -f docker/gristfdw/Dockerfile \
            --build-arg POSTGRES_VERSION=13 \
            --build-arg MULTICORN_VERSION=2.4 \
            -t gristfdw:main-bullseye-postgres13-multicorn2.4 \
            .
      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        run: |
          docker push gristfdw/gristfdw:main-bullseye-postgres13-multicorn2.4
